baseURL = 'https://technicallybeautiful.ca/'
languageCode = 'en-us'
title = 'Technically Beautiful Ottawa'
theme = 'PaperMod'

[[menu.main]]
name = "About"
url  = "/about/"
weight = 10

[[menu.main]]
name = "Contact"
url  = "/contact/"
weight = 20

[[menu.main]]
identifier = 'projects'
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
parent = "projects"
name   = "Shelter Pins"
url    = "projects/pins/"
weight = 31

[params]
  disableSpecial1stPost = true